application: independentcinemas
version: 2
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: cinema.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico