application: independentcinemas
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /cms/
  static_dir: cms

- url: /static/
  static_dir: static

- url: /.*
  script: cinema.py

builtins:
  - datastore_admin: on
  - appstats: on